apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: argocd
  sources:
    - repoURL: https://argoproj.github.io/argo-helm 
      chart: argo-cd
      targetRevision: 7.8.14  
      helm:      
        valueFiles:
          - $values/.platform/mgnt.yaml
    - repoURL: https://github.com/Davitron/demo-platform-argocd.git
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
