apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crossplane
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters: {}
          - list:
              elements:
                - appName: crossplane
                  path: ./charts
                  namespace: crossplane
                - appName: crossplane-config
                  path: ./crossplane-config-chart
                  namespace: crossplane-config
  template:
    metadata:
      name: '{{ .appName }}-{{ if eq .name "in-cluster" }}mgnt{{ else }}{{ .metadata.labels.env }}{{ end }}'
    spec:
      project: platform-crossplane
      source:
        repoURL: https://github.com/Davitron/demo-platform-crossplane.git
        targetRevision: HEAD
        path: '{{ .path }}'
        helm:
          valueFiles:
            - "../{{ if eq .name \"in-cluster\" }}.platform/mgnt.yaml{{ else }}.platform/{{ .metadata.labels.env }}.yaml{{ end }}"
          values: |
            globals:
              {{- $filtered := dict }}
              {{- range $k, $v := .metadata.annotations }}
                {{- if and (ne $k "kubectl.kubernetes.io/last-applied-configuration") (ne $k "managed-by") }}
                  {{- $_ := set $filtered $k $v }}
                {{- end }}
              {{- end }}
              {{- toYaml $filtered | nindent 2 }}
      destination:
        server: '{{ .server }}'
        namespace: '{{ .namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - RespectIgnoreDifferences=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: crossplane-validator-crossplane
          jsonPointers:
            - /webhooks/0/failurePolicy
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: crossplaned-default-validator
          jsonPointers:
            - /webhooks/0/failurePolicy